networks:
  application:
    driver: bridge

services:
  db:
    image: mariadb
    container_name: db
    networks:
      - application
    volumes:
      - ./docker/services/mariadb/data:/var/lib/mysql
    environment:
      - TZ=America/Belem
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=url_shortener
#    ports:
#      - "3306:3306"
    restart: always

  app:
    image: node:lts
    container_name: app
    working_dir: /home/node/app
    volumes:
      - ./frontend/:/home/node/app
    environment:
      - TZ=America/Belem
    command: npm run start
    networks:
      - application
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - application
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - application