networks:
  application:
    driver: bridge

services:
  db:
    image: mariadb
    container_name: db_url_shortener
    networks:
      - application
    volumes:
      - ./docker/services/mariadb/data:/var/lib/mysql
    environment:
      - TZ=America/Belem
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=url_shortener
    ports:
      - "3306:3306"
    restart: always